# Generated by Django 4.0.5 on 2022-06-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_lift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargolift',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
