# Generated by Django 4.0.5 on 2022-07-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_lift', '0003_alter_cargolift_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargolift',
            name='brand',
        ),
        migrations.DeleteModel(
            name='CargoLiftBrand',
        ),
    ]
