# Generated by Django 4.0.5 on 2022-07-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_and_accesories', '0003_alter_partsandaccessories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsandaccessories',
            name='pdf_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
